# Generated by Django 5.0.1 on 2026-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="business_model",
            field=models.CharField(
                choices=[
                    ("B2B", "Business to Business"),
                    ("B2C", "Business to Consumer"),
                    ("C2C", "Consumer to Consumer"),
                ],
                default="B2C",
                help_text="Which portal this category belongs to",
                max_length=3,
            ),
        ),
    ]
