# Generated by Django 5.0.1 on 2026-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rfq",
            name="status",
            field=models.CharField(
                choices=[
                    ("unavailable", "Unavailable"),
                    ("pending", "Pending"),
                    ("responded", "Responded"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
